- name: Append to correct JS object
  run: |
    CATEGORY=$(echo "${{ github.event.inputs.category }}" | tr '[:upper:]' '[:lower:]')
    FILE="index.html"

    # Choose variable name
    case "$CATEGORY" in
      blog) VAR_NAME="blogs" ;;
      tweet) VAR_NAME="Tweet" ;;
      book) VAR_NAME="books" ;;
      paper) VAR_NAME="R_papers" ;;
      personal) VAR_NAME="personalwriteups" ;;
      *) echo "Unknown category: $CATEGORY" && exit 1 ;;
    esac

    TITLE=$(echo "${{ github.event.inputs.title }}" | sed 's/"/\\"/g')
    URL=$(echo "${{ github.event.inputs.url }}" | sed 's/[\/&]/\\&/g')

    # Debug: print what we're about to insert
    echo "Adding \"$TITLE\": \"$URL\" to $VAR_NAME"

    # Append to the correct JS object using Perl (better multiline support)
    perl -0777 -i -pe "s/(let\s+$VAR_NAME\s*=\s*{)(.*?)(\n})/\$1\$2,\n  \\\"$TITLE\\\": \\\"$URL\\\"\$3/s" $FILE
