name: Add new resource

on:
  workflow_dispatch:
    inputs:
      category:
        description: "Category (blog, tweet, book, paper, personal)"
        required: true
        type: string
      title:
        description: "Title of the item"
        required: true
        type: string
      url:
        description: "URL of the item"
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Append to correct JS object
        run: |
          CATEGORY=$(echo "${{ github.event.inputs.category }}" | tr '[:upper:]' '[:lower:]')
          FILE="index.html"

          case "$CATEGORY" in
            blog) VAR_NAME="blogs" ;;
            tweet) VAR_NAME="Tweet" ;;
            book) VAR_NAME="books" ;;
            paper) VAR_NAME="R_papers" ;;
            personal) VAR_NAME="personalwriteups" ;;
            *) echo "Unknown category: $CATEGORY" && exit 1 ;;
          esac

          TITLE=$(echo "${{ github.event.inputs.title }}" | sed 's/"/\\"/g')
          URL=$(echo "${{ github.event.inputs.url }}" | sed 's/[\/&]/\\&/g')

          echo "Appending \"$TITLE\": \"$URL\" to $VAR_NAME"

          perl -0777 -i -pe "s/(let\s+$VAR_NAME\s*=\s*{)(.*?)(\n})/\$1\$2,\n  \\\"$TITLE\\\": \\\"$URL\\\"\$3/s" "$FILE"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "bot@users.noreply.github.com"
          git add index.html
          git commit -m "Add ${{ github.event.inputs.title }} to ${{ github.event.inputs.category }}"
          git push

